const data = {
  products: [
    {
      // _id: '1',
      name: 'Ambrosia',
      slug: 'Wig-rosa',
      category: 'Pelucas',
      image: '/images/p1.jpg', // 679px × 829px
      price: 95,
      countInStock: 5,
      brand: 'wig',
      rating: 5.0,
      numReviews: 10,
      description: 'Peluca rosada con degradación en negro en la raíz, capul y malla de encaje, no es lace front, 24 pulgadas de longitud, ondulada.Incluye red para cabello.Termoresistencia: 160°c. Puede ser usada para en diario.',
    },
  
    {
      // _id: '2',
      name: 'Fire my light',
      slug: 'wig-rubia-crespa',
      category: 'Pelucas',
      image: '/images/p2.jpg',
      price: 135,
      countInStock: 0,
      brand: 'wig',
      rating: 4.0,
      numReviews: 10,
      description: 'Peluca sintética rizada, malla interior con clips, cabello rubio oscuro con degradación en tono café oscuro, lace frontal en T, hasta ma raíz, 24 pulgadas de longitud. Incluye red para el cabello. No se recomienda planchar pero su termorresistencia es de 160°c.puede usarse para el diario. ',
    },
    {
      // _id: '3',
      name: 'Comme des darcons',
      slug: 'wig-azul-blanco',
      category: 'Pelucas',
      image: '/images/p3.jpg',
      price: 180,
      countInStock: 15,
      brand: 'Posh',
      rating: 4.5,
      numReviews: 14,
      description: 'Peluca lisa, malla interior con clips, cabello rubio con degradación en azul claro y azul rey, 150% de densidad, lace frontal HD en T de 1.5x4 pulgadas(de oreja a oreja y raíz cosida a mano), 24 pulgadas de longitud. Incluye red para el cabello. Termorresistencia: 180°c. Puede usarse para el diario.',
    },
    {
      // _id: '4',
      name: 'Orange trees',
      slug: 'wig-naranja-crespa',
      category: 'Pelucas',
      image: '/images/p4.jpg',
      price: 105,
      countInStock: 5,
      brand: 'Puma',
      rating: 3.0,
      numReviews: 10,
      description: 'Peluca naranja con raíz oscura, con malla de encaje suizo, lace frontal pequeño, 26 pulgadas, rizada.Termoresistencia: 180°c. Incluye red para cabello.',
    },
    {
      // _id: '5',
      name: 'I am not a robot',
      slug: 'wig-cafe-morada',
      category: 'Pelucas',
      image: '/images/p5.jpg',
      price: 80,
      countInStock: 1,
      brand: 'Posh',
      rating: 4.0,
      numReviews: 8,
      description: 'Peluca rojiza con mechones púrpura , larga, con malla de encaje con capul, no es lace front, 22 pulgadas, lisa. Incluye red para cabello. Termoresistencia: 160°c.',
    },
    {
      // _id: '6',
      name: 'She thunderstroms',
      slug: 'wig-naranja-ondulada',
      category: 'Pelucas',
      image: '/images/p6.jpg',
      price: 145,
      countInStock: 3,
      brand: 'Wig',
      rating: 4.5,
      numReviews: 9,
      description: 'Peluca ondulada en tono naranja cobrizo con raíz en degradación en tono negro, malla interior con clips, 130% de densidad, lace frontal HD en T de 1.5x4 pulgadas(de oreja a oreja con simulación de baby hairs precortados), 26 pulgadas de longitud. Incluye red para el cabello. : 180°c.  para el diario',
    },
    // {
    //   // _id: '7',
    //   name: 'The outsider',
    //   slug: 'wig-rubia-lisa',
    //   category: 'Pelucas',
    //   image: '/images/p7.jpg',
    //   price: 125,
    //   countInStock: 9,
    //   brand: 'Posh',
    //   rating: 4.5,
    //   numReviews: 10,
    //   description: 'Peluca en tono gris medio con raíz en tono negro, 30 pulgadas de longitud, lisa sin capul. Lace frontal en t (de orejas hasta la raíz). Malla interior de encaje suizo con ganchos de ajuste.Incluye gorro para cabello.Termoresistencia: 150°c.Puede usarse para el diario.',
    // },    
    {
      // _id: '8',
      name: 'Corset Wildest Dreams',
      slug: 'corset-beige',
      category: 'Ropa',
      image: '/images/p8.jpg',
      price: 90,
      countInStock: 0,
      brand: 'Posh',
      rating: 4.5,
      numReviews: 10,
      description: 'Corset de estilo Victoriano con encaje en la parte superior, color beige, ajuste en la parte trasera y botones delanteros. Disponible en tallas S. ',
    },
    {
      // _id: '9',
      name: 'Arnés Cold Heart',
      slug: 'arnes',
      category: 'Ropa',
      image: '/images/p9.jpg',
      price: 40,
      countInStock: 5,
      brand: 'Posh',
      rating: 5.0,
      numReviews: 0,
      description: '.',
    },    
    {
      // _id: '10',
      name: 'Corset Enchanted',
      slug: 'corset-lila',
      category: 'Ropa',
      image: '/images/p10.jpg',
      price: 85,
      countInStock: 2,
      brand: 'Posh',
      rating: 3.9,
      numReviews: 1,
      description: 'Corset de estilo Victoriano con encaje en la parte superior, color lila con patrón en rosa, ajuste en la parte trasera y botones delanteros. Disponible en tallas S y M. ',
    },
  ],
};
export default data;